# Railway deployment configuration for MIT Manipal Reddit
[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install] 
cmds = ["npm install"]

[phases.build]
cmds = ["npm run heroku-postbuild"]
